### ISSUE TITLE
analyze deprication error

### ISSUE THREAD

**Issue by geetee24** [gearsandcode/protractor-axe-html-report-plugin#13]
can you please fix this in index.js

bad: builder.analyze((results) => {

should be:    builder.analyze (( err, results ) => {

**Comment by gearsandcode** [comment]
Create a PR and I’ll happily accept it.

**Comment by gearsandcode** [comment]
There is no ETA. If you need it fixed, create a fork, fix it there and then create a PR against this project. I'll then review it and approve it if it doesn't break anything. Outside of that, like most open source developers, I have a full time gig that is keeping me busy.

**Comment by geetee24** [comment]
i cant get the source code to work so it is out of my hands.

**Comment by geetee24** [comment]
when your plugin, we get typescript error: TS2304: Cannot find name 'runAxeTest'.

Any ideas?
