### ISSUE TITLE
axe.analyze deprecation warning

### ISSUE THREAD

**Issue by marshallmick007** [gearsandcode/protractor-axe-html-report-plugin#9]
While using the latest `axe-webdriverjs`, using axe.analyze prints a deprecation warning

```
axe-webdriverjs deprecated Error must be handled as the first argument of axe.analyze. See: #83 node_modules\protractor-axe-html-report-plugin\index.js:69:19
```

See: https://github.com/dequelabs/axe-webdriverjs/pull/83

**Comment by geetee24** [comment]
i too have same issue.  code fails to run

**Comment by geetee24** [comment]
can you please fix this?

bad: builder.analyze((results) => {

should be:    builder.analyze (( err, results ) => {

**Comment by mohkumar** [comment]
issue still persists. Is someone looking for this fix ?
